server:
  port: 8081
  # SocketIO??
# SocketIO??
socket:
  # SocketIO??
  port: 9090
  # ?????
  workCount: 100
  # ??????
  allowCustomRequests: true
  # ????????(??)???10??HTTP?????ws??????
  upgradeTimeout: 10000
  # Ping??????(??)???60??????????????????????????
  pingTimeout: 60000
  # Ping????(??)???25???????????????????
  pingInterval: 25000
  # ??HTTP????????
  maxHttpContentLength: 1048576
  # ?????????????????????????????
  maxFramePayloadLength: 1048576

    #swagger
springdoc:
  api-docs:
        #????????
    enabled: true
        #swagger??????
    path: /api-docs
  swagger-ui:

        #???swagger?????????http?127.0.0.1:8080/test???????swagger??
    path: /testSwagger
      #?????
  packages-to-scan: com.kate.demo
      #??????????????????????
#      group-configs:
#        #???
#        - group: admin
#          #?????
#          pathsToMatch: /admin/**
#          #???
#        - group: user
#          #??????
#          packagesToScan: com.

